#data_loading:
#  folder_path: "C:\\Users\\abhay.bhandari\\Jupyter files\\Deployment practice\\Deployed env\\Agencies"
#
#data_ingestion:
#  train_data_path: "C:\\Users\\abhay.bhandari\\Jupyter files\\Caresmartz360\\src\\components\\agency\\train.csv"
#  test_data_path: "C:\\Users\\abhay.bhandari\\Jupyter files\\Caresmartz360\\src\\components\\agency\\test.csv"
#  raw_data_path: "C:\\Users\\abhay.bhandari\\Jupyter files\\Caresmartz360\\src\\components\\agency\\sales.csv"

data:
  data_folder: C:\Users\abhay.bhandari\Jupyter files\Caresmartz360\Agencies
  data_store_path: C:\Users\abhay.bhandari\Jupyter files\Caresmartz360\src\components\agency
  train_data_path: C:\Users\abhay.bhandari\Jupyter files\Caresmartz360\src\components\agency\train.csv
  test_data_path: C:\Users\abhay.bhandari\Jupyter files\Caresmartz360\src\components\agency\test.csv
  raw_data_path: C:\Users\abhay.bhandari\Jupyter files\Caresmartz360\src\components\agency\sales.csv
  preprocessor_file: C:\Users\abhay.bhandari\Jupyter files\Caresmartz360\src\components\artifacts\preprocessor.pkl
  start_date: '2023-09-01'

  model:
    save_folder: artifacts
    trained_model_file: trained_model.pkl


#arima_model:
#  order: [1, 1, 1]
#  seasonal: false
#  stepwise: true
#  trace: false
#
#sarima_model:
#  order: [1, 1, 1]
#  seasonal_order: [1, 1, 1, 12]
#  m: 12
#  stepwise: true
#  trace: false
#
#auto_reg_model:
#  lags: 1
#
#linear_regression_model:
  # Add any hyperparameters specific to Linear Regression here

